name: Gambit mutation testing

on:
  workflow_dispatch:

jobs:
  run-mutation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Gambit
        run: |
          wget -O gambit https://github.com/Certora/gambit/releases/download/v1.0.5/gambit-linux-v1.0.5
          chmod +x gambit
          sudo mv gambit /usr/local/bin/

      - name: Install packages
        run: yarn

      - name: Install solc-select
        run: |
          pip install solc-select
          solc-select install 0.8.16
          solc-select use 0.8.16

      - name: Prepare config file
        run: yarn prepare:mutation:ci-config

      - name: Run mutation tests
        run: |
          yarn test:mutation
